### ISSUE TITLE
unrar folder filling up.

### ISSUE THREAD

**Issue by richmobile** [NNTmux/newznab-tmux#806]
No matter if set to tmpfs or left to the physical store, /var/www/NNTmux/resources/tmp/unrar gradually fills to disk capacity while performing deep rar inspection.

Manually writing and deleting on the share works fine.

 - Ubuntu 16.04.5
 - PHP 7.2.12-1
 - NNTmux master

**Comment by richmobile** [comment]
No matter if set to tmpfs or left to the physical store, /var/www/NNTmux/resources/tmp/unrar gradually fills to disk capacity while performing deep rar inspection.

Manually writing and deleting on the share works fine.

**Comment by DariusIII** [comment]
Closing this as issues has been resolved.

**Comment by jangrewe** [comment]
@DariusIII not sure what you changed, but this is definitely still an issue. I have a 4G tmpfs i need to regularly wipe.

**Comment by Fossil01** [comment]
I had the same problem. I changed the code to rm -rf that folders contents after every run.
