### ISSUE TITLE
New install fails with error 'Unable to add admin user!'

### ISSUE THREAD

**Issue by boppen** [NNTmux/newznab-tmux#928]
Ubuntu 18.04, PHP 7.3.2, Apache, MariaDB 10.2.22

Followed the installation guide, copied .env.example to .env and filled in the fields that the guide told me to. When running php artisan nntmux:install it fails with the following error:

Address in mailbox given [] does not comply with RFC 2822, 3.6.2.Unable to add admin user!
NNTmux installation failed. Fix reported problems and try again

Admin user settings in env:
ADMIN_USER=\<username\>
ADMIN_PASS=\<password\>
ADMIN_EMAIL=\<name\>@\<domain\>

Looked in the user table and the user is actually inserted (with the correct email). Unfortunatly I don't know enough PHP to debug and track down the problem but hopefully the information given should be enough.

**Comment by Sweepr** [comment]
Just fill in a valid e-mail, @ isn't valid

**Comment by Sweepr** [comment]
Also a user and password is required, otherwise you can't login.

**Comment by boppen** [comment]
They were filled in, I just forgot about markdown so they looked empty, edited  :)

**Comment by DariusIII** [comment]
It's actually a problem with observer and how user is created, not install itself. Will fix later today.

**Comment by lloot** [comment]
same problem here

**Comment by lloot** [comment]
> 
> 
> Ubuntu 18.04, PHP 7.3.2, Apache, MariaDB 10.2.22
> 
> Followed the installation guide, copied .env.example to .env and filled in the fields that the guide told me to. When running php artisan nntmux:install it fails with the following error:
> 
> Address in mailbox given [] does not comply with RFC 2822, 3.6.2.Unable to add admin user!
> NNTmux installation failed. Fix reported problems and try again
> 
> Admin user settings in env:
> ADMIN_USER=<username>
> ADMIN_PASS=<password>
> ADMIN_EMAIL=<name>@<domain>
> 
> Looked in the user table and the user is actually inserted (with the correct email). Unfortunatly I don't know enough PHP to debug and track down the problem but hopefully the information given should be enough.

how did u fix it>?

**Comment by DariusIII** [comment]
This has been fixed in commit https://github.com/NNTmux/newznab-tmux/commit/e6b4bc5a6e774ab51c7bb0a88dcad4e25a66442f as stated above. 

It is in dev branch. I am closing this.

**Comment by lloot** [comment]
i have used the commited file however still same error any ideas?

**Comment by lloot** [comment]
reddid everything clean install same error :(

**Comment by DrakeJones** [comment]
Same error.

**Comment by DariusIII** [comment]
Check admin email address in your .env file.

**Comment by DrakeJones** [comment]
Thanks.  Did.  Doesn’t seem to be the problem.  Bazaar thing: I can access all admin functionality directly via http://localhost/admin/, but I can’t login as a user/admin via the login page.  I even added a new admin, to no avail.  Added a “user” and localhost/login throws the error below. Could this have something to do with it?  Maybe not.  (Have to get some sleep now.  I’ll check back tomorrow).

 

Illuminate\Contracts\Container\BindingResolutionException

Target class [PragmaRX\Firewall\Middleware\FirewallBlacklist] does not exist.

http://localhost/

 

 

/var/www/NNTmux/

Telescope

Illuminate\Contracts\Container\BindingResolutionException

Target class [PragmaRX\Firewall\Middleware\FirewallBlacklist] does not exist.

http://localhost/

 

        45

        vendor/laravel/framework/src/Illuminate/Container/Container.php

        Illuminate\Container\Container

        :805

 

        1

        public/index.php

        :7

 

Illuminate\Container\Container::build

vendor/laravel/framework/src/Illuminate/Container/Container.php:805

 

     *

 

     * @throws \Illuminate\Contracts\Container\BindingResolutionException

 

     */

 

    public function build($concrete)

 

    {

 

        // If the concrete type is actually a Closure, we will just execute it and

 

        // hand back the results of the functions, which allows functions to be

 

        // used as resolvers for more fine-tuned resolution of these objects.

 

        if ($concrete instanceof Closure) {

 

            return $concrete($this, $this->getLastParameterOverride());

 

        }

 

 

        try {

 

            $reflector = new ReflectionClass($concrete);

 

        } catch (ReflectionException $e) {

 

            throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);

 

        }

 

 

        // If the type is not instantiable, the developer is attempting to resolve

 

        // an abstract type such as an Interface or Abstract Class and there is

 

        // no binding registered for the abstractions so we need to bail out.

 

        if (! $reflector->isInstantiable()) {

 

            return $this->notInstantiable($concrete);

 

        }

 

 

        $this->buildStack[] = $concrete;

 

 

        $constructor = $reflector->getConstructor();

 

 

        // If there are no constructors, that means there are no dependencies then

 

        // we can just resolve the instances of the objects right away, without

**Comment by DariusIII** [comment]
Update to latest version, that firewall issue has been fixed.

**Comment by DrakeJones** [comment]
No joy.  Still can’t login.  Selecting “Contact” Button using Chrome throws the error shown immediately below, but oddly enough, Firefox throws a different error (shown further down).  I’m using Debian Buster, by the way.  Could I have misconfigured something?

 

CHROME ERROR

-------------------------------

/var/www/NNTmux/

Telescope

Illuminate\Contracts\Container\BindingResolutionException

Target class [PragmaRX\Firewall\Middleware\FirewallBlacklist] does not exist.

http://192.168.10.9/contact-us

 

        45

        vendor/laravel/framework/src/Illuminate/Container/Container.php

        Illuminate\Container\Container

        :805

 

        1

        public/index.php

        :7

 

Illuminate\Container\Container::build

vendor/laravel/framework/src/Illuminate/Container/Container.php:805

 

     *

 

     * @throws \Illuminate\Contracts\Container\BindingResolutionException

 

     */

 

    public function build($concrete)

 

    {

 

        // If the concrete type is actually a Closure, we will just execute it and

 

        // hand back the results of the functions, which allows functions to be

 

        // used as resolvers for more fine-tuned resolution of these objects.

 

        if ($concrete instanceof Closure) {

 

            return $concrete($this, $this->getLastParameterOverride());

 

        }

 

 

        try {

 

            $reflector = new ReflectionClass($concrete);

 

        } catch (ReflectionException $e) {

 

            throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);

 

       }

 

 

        // If the type is not instantiable, the developer is attempting to resolve

 

        // an abstract type such as an Interface or Abstract Class and there is

 

        // no binding registered for the abstractions so we need to bail out.

 

        if (! $reflector->isInstantiable()) {

 

            return $this->notInstantiable($concrete);

 

        }

 

 

        $this->buildStack[] = $concrete;

 

 

        $constructor = $reflector->getConstructor();

 

 

        // If there are no constructors, that means there are no dependencies then

 

        // we can just resolve the instances of the objects right away, without                                                     

 

 

FIREFOX ERROR

_______________________

 

Illuminate\Contracts\Container\BindingResolutionException: Target class [PragmaRX\Firewall\Middleware\FirewallBlacklist] does not exist. in file /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 805

 

#0 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build('PragmaRX\\Firewa...')

#1 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\Container\Container->resolve('PragmaRX\\Firewa...', Array, true)

#2 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Foundation\Application->resolve('PragmaRX\\Firewa...', Array)

#3 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\Container\Container->make('PragmaRX\\Firewa...', Array)

#4 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(160): Illuminate\Foundation\Application->make('PragmaRX\\Firewa...')

#5 /var/www/NNTmux/vendor/jrean/laravel-user-verification/src/Middleware/IsVerified.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#6 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Jrean\UserVerification\Middleware\IsVerified->handle(Object(Illuminate\Http\Request), Object(Closure))

#7 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#8 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))

#9 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#10 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))

#11 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#12 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\AuthenticateSession->handle(Object(Illuminate\Http\Request), Object(Closure))

#13 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#14 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))

#15 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#16 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))

#17 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#18 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))

#19 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#20 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))

#21 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#22 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))

#23 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))

#24 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))

#25 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))

#26 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))

#27 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))

#28 /var/www/NNTmux/vendor/genealabs/laravel-caffeine/src/Http/Middleware/LaravelCaffeineDripMiddleware.php(11): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#29 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): GeneaLabs\LaravelCaffeine\Http\Middleware\LaravelCaffeineDripMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))

#30 /var/www/NNTmux/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#31 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))

#32 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#33 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))

#34 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#35 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))

#36 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#37 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))

#38 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#39 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))

#40 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#41 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))

#42 /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))

#43 /var/www/NNTmux/public/index.php(7): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))

#44 {main}

**Comment by Fossil01** [comment]
`Target class [PragmaRX\Firewall\Middleware\FirewallBlacklist] does not exist.`

Try running the dev branch.

**Comment by DrakeJones** [comment]
The “Contact” button is working now, but I still can’t log in.  I must have misconfigured db permissions.  Any suggestions on where else to look?

**Comment by Fossil01** [comment]
Post logs from storage/logs to https://kopy.io

**Comment by DrakeJones** [comment]
Horizon.log https://kopy.io/g63zX

 

Laravel log https://kopy.io/VZUS5

**Comment by Fossil01** [comment]
The logs explain itself:

`  UnexpectedValueException  : The stream or file "/var/www/NNTmux/storage/logs/laravel-2020-04-13.log" could not be opened: chmod(): Operation not permitted`

Permissions error.

`Connection refused at /var/www/NNTmux/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:130)`

Either Redis is not running or the config is wrong.

**Comment by DrakeJones** [comment]
Yes indeedy.  Thank you.  I reconfigured Redis (status shown below). It’s up and running but still not connecting.  What are the proper permissions?  And, would that prevent login in to NNTmux? 

 

redis-server.service - Advanced key-value store

   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: 

   Active: activating (start) since Mon 2020-04-13 15:09:57 CEST; 50s ago

     Docs: http://redis.io/documentation,

           man:redis-server(1)

Cntrl PID: 3132 (redis-server)

    Tasks: 4 (limit: 4661)

   Memory: 7.1M

   CGroup: /system.slice/redis-server.service

           └─3132 /usr/bin/redis-server *:6379

 

Apr 13 15:09:57 pino systemd[1]: Starting Advanced key-value store...

Apr 13 15:09:57 pino redis-server[3132]: 3132:C 13 Apr 2020 15:09:57.891 # oO0OoO0OoO

Apr 13 15:09:57 pino redis-server[3132]: 3132:C 13 Apr 2020 15:09:57.891 # Redis vers

Apr 13 15:09:57 pino redis-server[3132]: 3132:C 13 Apr 2020 15:09:57.891 # Configurat

Apr 13 15:09:57 pino redis-server[3132]: 3132:M 13 Apr 2020 15:09:57.893 * Running mo

Apr 13 15:09:57 pino redis-server[3132]: 3132:M 13 Apr 2020 15:09:57.893 # Server ini

Apr 13 15:09:57 pino redis-server[3132]: 3132:M 13 Apr 2020 15:09:57.893 # WARNING ov

Apr 13 15:09:57 pino redis-server[3132]: 3132:M 13 Apr 2020 15:09:57.893 # WARNING yo

Apr 13 15:09:57 pino redis-server[3132]: 3132:M 13 Apr 2020 15:09:57.893 * Ready to a

~

**Comment by Fossil01** [comment]
Post logs. Dont use e-mail, it's shit.

**Comment by DrakeJones** [comment]
Got it.  https://kopy.io/pXTn4
Running nZEDb at the moment.  It's stable and an amazing thing, but I'm not overjoyed with it at the moment.

**Comment by Fossil01** [comment]
Your Redis install or config is still wrong. Try following the Installation guide again.

**Comment by DrakeJones** [comment]
I'll reinstall.  It's learning experience.  Thank you for your time
